version: '3.7'

services:

  sample:
    container_name: my-dugut
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
