version: '3.7'

services:

  sample:
    container_name: my-dugut
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=production
      - REACT_APP_DEV_API_KEY=AIzaSyC7lJ2lmQOfGzhdRvMgDrJHaU5qcVRqgPA
      - REACT_APP_DEV_AUTH_DOMAIN=savvy-palace-259505.firebaseapp.com
      - REACT_APP_DEV_DATABASE_URL=https://savvy-palace-259505.firebaseio.com
      - REACT_APP_DEV_PROJECT_ID=savvy-palace-259505
      - REACT_APP_DEV_STORAGE_BUCKET=savvy-palace-259505.appspot.com
      - REACT_APP_DEV_MESSAGING_SENDER_ID=978131684388
      - REACT_APP_PROD_API_KEY=AIzaSyC7lJ2lmQOfGzhdRvMgDrJHaU5qcVRqgPA
      - REACT_APP_PROD_AUTH_DOMAIN=savvy-palace-259505.firebaseapp.com
      - REACT_APP_PROD_DATABASE_URL=https://savvy-palace-259505.firebaseio.com
      - REACT_APP_PROD_PROJECT_ID=savvy-palace-259505
      - REACT_APP_PROD_STORAGE_BUCKET=savvy-palace-259505.appspot.com
      - REACT_APP_PROD_MESSAGING_SENDER_ID=978131684388
      - PUBLIC_URL=https://my.dugut.app
